using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum AbilityTierEnum
{
    TIER1, TIER2, TIER3
}

public enum AbilityCategoryEnum
{
    OFFENSIVE, DEFENSIVE, AGILITY
}

public enum AbilityTypeEnum
{
    ABILITY, DAMAGEUP, DEFENSEUP, ATTACKSPEEDUP, HITPOINTSUP, SPEEDUP
}

public enum AbilityEnum
{
    DASH, INVULNERABLEDASH, SLOW, SPEED, PARRYDEFENSE, PARRYEXPLOSION, INVULNERABLEPARRY, PARALIZATIONPARRY, PARRYSPEED, DUALATTACK, FRENZYATTACK, STABATTACK, STUNATTACK, WAVEATTACK, WHIRLWINDATTACK, RECALL,
    CLONE, CANCEL
}

public enum ShopSlotType
{
    BUY, SELL
}